name: "ollama"
type: "local"
baseUrl: "http://localhost:11434"
authType: "none"
parameters:
  baseUrlEnv: "NEXT_PUBLIC_OLLAMA_BASE_URL"
  model: "phi-4-deepseek"
  temperature: 0.7
  maxTokens: 2048
rateLimit:
  requestsPerMinute: 30
  maxConcurrent: 2
